###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "first last",
  "number": "123-2829182"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123-2829182"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "just a name"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "121212"
}

###
PUT http://localhost:3001/api/persons/6244a19b782143b035aafac7
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "000"
}

###
DELETE http://localhost:3001/api/persons/4